version: '3.9'

services:
  finantracker_db:
    container_name: finantracker_db
    image: bitnami/postgresql:17.4.0
    environment:
      POSTGRES_USER: finantracker
      POSTGRES_PASSWORD: finantracker
      POSTGRES_DB: finantracker_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
